[package]
name = "rustos"
version = "0.1.0"
authors = ["drakemain <demain1990@gmail.com>"]

[dependencies]
bootloader_precompiled = "^0.2.0"
volatile = "^0.2.0"

[profile.dev]

[profile.release]

[package.metadata.bootimage]
default-target = "x86_64_rustos.json"